// Autogenerated by Thrift Compiler (0.9.1)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package edam

import (
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/colbygk/evernote-sdk-golang/edam"
	"math"
)

// (needed to ensure safety because of naive import list construction.)
var _ = math.MinInt32
var _ = thrift.ZERO
var _ = fmt.Printf

var _ = edam.GoUnusedProtection__
var _ = edam.GoUnusedProtection__
var _ = edam.GoUnusedProtection__
var _ = edam.GoUnusedProtection__

func init() {
}
